# 룰렛 서바이벌 by WaMel_ (디스코드: 종현#7737)
# 워멜 유튜브: https://www.youtube.com/@WaMel04

# config가 손상될시 플러그인이 비활성화됩니다. 이 경우 config를 삭제 후 플러그인을 리로드해주세요.
# config를 리로드하고 싶을시 /roul reload를 입력해주세요!
# 게임 중에는 변경된 값이 적용되지 않습니다. 이 경우, /roul stop으로 게임을 종료하신 후 다시 시작해주세요.

# 룰렛 주기 최솟값
# ====================
# 룰렛이 돌아가는 주기를 설정합니다.
# 룰렛 실행시 주기는 (최소) ~ (최대) 사이의 정수로 매번 정해집니다.
# 단위: 초
roulette_period_min: 150

# 룰렛 주기 최댓값
# ====================
# 룰렛이 돌아가는 주기를 설정합니다.
# 룰렛 실행시 주기는 (최소) ~ (최대) 사이의 정수로 매번 정해집니다.
# 단위: 초
roulette_period_max: 240

# 플레이어 목숨
# ====================
# 플레이어의 목숨을 설정합니다.
# 목숨을 모두 소진시 해당 플레이어는 관전 모드로 전환됩니다.
player_lifes: 5

# 드랍률
# ====================
# 드랍률을 설정합니다.
# 드랍률이 높을 수록 게임을 더 빠르게 진행할 수 있을 거예요!
drop_multiple: 3